name: 'xray-action'
description: 'GitHub action to import test results into "Xray" - A complete Test Management tool for Jira.'
author: 'Mike Penz'
branding:
  icon: 'check-circle'  
  color: 'green'
inputs:
  xrayCloud:
    required: false
    default: "true"
    description: 'Defines which variant of Xray to target at [cloud vs Server/DC]'
  xrayBaseUrl:
    required: false
    description: 'Defines the base URL for Xray Server/DC, could be used to change XRay Data region for XRay Cloud (required if xrayCloud="false")'
  username:
    required: false
    description: 'Xray API client id (cloud) or Jira username (Server/DC). (Required for xrayCoud)'
  password:
    required: false
    description: 'Xray API client secret (cloud) or Jira password (Server/DC). (Required for xrayCoud)'
  xrayToken:
    required: false
    description: 'Xray Personal Access Token. If provided username/password are ignored. (Xray Server/DC only)'
  testPaths:
    required: true
    description: 'A `glob` pattern, to find all test results which should get imported.'
    default: "**/test-results/test/TEST-*.xml"
  testMerge:
    required: false
    description: 'When multiple test reports are found, they will be automatically merged into a single test report file. Only supported for: ["junit"]'
    default: "true"
  testFormat:
    description: 'The format of the to be imported data. ["xray", "cucumber", "behave", "junit", "testng", "nunit", "xunit", "robot", "bundle"].'
    default: "junit"
  testExecKey:
    description: 'Key of the Test Execution.'
    required: true
  projectKey:
    description: 'Key of the project where the Test Execution (if the testExecKey parameter was not provided) and the tests (if they are not created yet) are going to be created.'
    required: true
  testPlanKey:
    description: 'Key of the Test Plan; if you specify the Test Plan, the Tests will be added automatically to the Test Plan if they are not part of it.'
    required: false
  testEnvironments:
    description: 'A string containing a list of test environments separated by ";". This is not supported for cloud.'
    required: false
  revision:
    description: 'Source code and documentation version used in the test execution.'
    required: false
  fixVersion:
    description: 'The Fix Version associated with the test execution (it supports only one value).'
    required: false
  combineInSingleTestExec: 
    description: 'If no `testExecKey` is provided, it will generate a testExec with the first import, and reuse the same for all other imports.'
    required: false
    default: "false"
  failOnImportError:
    description: 'Defines if the action should fail if an import error occurred.'
    required: false
    default: "false"
  continueOnImportError:
    description: 'Defines if the action should continue after a single import error occurred.'
    required: false
    default: "true"
  importParallelism:
    description: 'Specifies the level of parallelism to import to Xray.'
    required: false
    default: "2"
  responseTimeout:
    description: 'Specifies the maximum duration for a request (in milliseconds) to wait for a response to execute before timing out. The default is 60 seconds.'
    required: false
    default: "60000"
  importRetryLimit:
    description: 'Specifies the maximum number of retries for failed import requests. The default is 2.'
    required: false
    default: "2"
  testExecutionJson:
    description: 'Links to a json file, defining the meta information to create the test execution ticket.'
    required: false
  testJson:
    description: 'Links to a json file, defining the meta information to create the test tickets.'
    required: false
outputs:
  count:
    description: 'The count of imported files.'
  failed:
    description: 'The count of failed imports.'
  completed:
    description: 'The count of completed imports.'
  errorMessage:
    description: 'The message of failed imports.'
  errorStatusCode:
    description: 'The status code of failed imports.'
runs:
  using: 'node20'
  main: 'dist/index.js'
